name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy
      uses: easingthemes/ssh-deploy@v5.0.3
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SCRIPT_AFTER: |
          set -e
          fuser -k 8080/tcp || true
          cd /home/${{ secrets.REMOTE_USER }}/
          cat > ./config.json << EOF
          ${{ secrets.DEPLOY_CONFIG }}
          EOF
          go build -o LiteChatServer
          screen -dmS LiteChatServerSession bash -c './LiteChatServer'
          sleep 5
          if ! pgrep LiteChatServer > /dev/null; then
            echo "LiteChatServer failed to start."
            screen -S LiteChatServerSession -X stuff "^C"
            exit 1
          fi
          echo "LiteChatServer started successfully."
